Login/logout react
wolox-training/ge-react-native pull request #5
Opened 2017-12-12 19:29 UTC by gon-escalante

## Summary
Added a login screen working with the books API and dropdowns for the profile and notifications. The profile has a logout button working and a mocked profile button. The notifications dropdown has one mocked notification. Also the WBooks logo now redirects you to the dashboard.

## ScreenShots
![peek 2017-12-12 16-22](https://user-images.githubusercontent.com/34032882/33903952-c89e140e-df58-11e7-87f3-88f09b86ecaf.gif)

## Trello Card
https://trello.com/c/8gRpB8HH/9-login-layout

2017-12-14 14:06 UTC, ignaciosantise requested changes

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +    <Link to='/'><img
Use the `routes` constant here

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +    {localStorage.getItem('isLoggedIn') &&
define a file for all localStorage functions, maybe in `utils` or `config` folder

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +    localStorage.removeItem('accessToken');
move these functions to a local storage file

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +  triggerProfileDropdown = (e) => {
if you dont need `e`, remove it from params

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +class Menu extends React.Component{
`import React, { Component } from 'react'`;

and

`class Menu extends Component {`

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +  }
you could simplify this using `prevState`

```
this.setState(prevState => {
   if(prevState.showProfileDropdown) {
      this.profileDropdownMenu.focus();
   }
   return { showProfileDropdown: !prevState.showProfileDropdown };
}
```
Read this!
https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +  triggerNotificationsDropdown = (e) => {
remove `e` from params

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +  }
same refactor using prevState

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/components/Header/index.js
> +        { !this.state.isLoggedIn && <Redirect to='/'/> }
do you need this?

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/index.js
> +const PrivateRoute = ({ component: Component, ...rest }) => (
👏

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/screens/bookDetail/index.js
> +
good line! 😆

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/screens/login/index.js
> +  validatePass(pass){
move both validation functions to `utils/validations.js` and import them here

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/screens/login/index.js
> +  }
`this.setState({ mailError: !this.validateEmail(e.target.value) });`

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/screens/login/index.js
> +  }
`this.setState({ passLengthError: !this.validatePass(e.target.value) });`

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/screens/login/index.js
> +    const { from } = this.props.location.state || { from: { pathname: ROOT } }
`const from =  this.props.location.state.from || { pathname: ROOT }` ?

2017-12-14 14:06 UTC, ignaciosantise commented on wbooks/src/app/screens/login/index.js
> +        <p className="login-error">You must log in to view the page at {from.pathname}</p>
the app is in spanish 🇪🇸

2017-12-14 17:26 UTC, gon-escalante commented on wbooks/src/app/screens/bookDetail/index.js
> +
vital

2017-12-14 17:34 UTC, gon-escalante commented on wbooks/src/app/screens/login/index.js
> +    const { from } = this.props.location.state || { from: { pathname: ROOT } }
makes sense

2017-12-15 14:50 UTC, ignaciosantise approved these changes

2017-12-15 19:40 UTC, merged